// فضفضة - تشفير + JWT - الإبقاء على كل شيء كما هو
export async function onRequest({request, env}) {
  const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Content-Type':'application/json'};
  if(request.method==='OPTIONS') return new Response(null,{headers:cors});
  const DB=env.DB; const b=await request.json().catch(()=>({})); const {phone,username,emoji,adminPass}=b;
  async function sha256(s){const buf=await crypto.subtle.digest('SHA-256', new TextEncoder().encode(s));return [...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,'0')).join('');}
  async function signJWT(p){const h=btoa(JSON.stringify({alg:'HS256',typ:'JWT'})).replace(/=/g,'');const b64=btoa(JSON.stringify({...p,exp:Date.now()+2592000000})).replace(/=/g,'');const data=`${h}.${b64}`;const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.JWT_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(data));const sigB64=btoa(String.fromCharCode(...new Uint8Array(sig))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');return `${data}.${sigB64}`;}
  if(!phone) return new Response(JSON.stringify({error:'رقم مطلوب'}),{status:400,headers:cors});
  if(username?.toLowerCase()==='admin'||phone==='01013200000'){const ih=await sha256(adminPass||''); if(ih!=='82a10f2ca79e1d9740da9c7b49b26eeee57c78c04f7fb4eb9c7c3d618392e5e4') return new Response(JSON.stringify({error:'باسورد غلط'}),{status:401,headers:cors}); let admin=await DB.prepare("SELECT * FROM users WHERE phone='01013200000'").first(); if(!admin){await DB.prepare("INSERT INTO users (phone,username,emoji,points,role,created_at) VALUES ('01013200000','أحمد','🛡️',0,'admin',?1)").bind(Date.now()).run(); admin=await DB.prepare("SELECT * FROM users WHERE phone='01013200000'").first();} const token=await signJWT({phone:admin.phone,role:'admin'}); return new Response(JSON.stringify({ok:true,user:admin,token}),{headers:cors});}
  let user=await DB.prepare("SELECT * FROM users WHERE phone=?1").bind(phone).first(); if(user){const token=await signJWT({phone:user.phone,role:user.role}); return new Response(JSON.stringify({ok:true,user,token}),{headers:cors});}
  try{await DB.prepare("INSERT INTO users (phone,username,emoji,points,role,created_at) VALUES (?1,?2,?3,0,'user',?4)").bind(phone,username,emoji||'✨',Date.now()).run();}catch(e){return new Response(JSON.stringify({error:'الرقم موجود'}),{status:409,headers:cors});}
  user=await DB.prepare("SELECT * FROM users WHERE phone=?1").bind(phone).first(); const token=await signJWT({phone:user.phone,role:user.role}); return new Response(JSON.stringify({ok:true,user,token}),{headers:cors});
}
