export async function onRequest({request, env}) {
  const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Content-Type':'application/json'};
  if(request.method==='OPTIONS') return new Response(null,{headers:cors});
  const DB=env.DB;
  if(request.method==='GET'){const r=await DB.prepare("SELECT * FROM posts ORDER BY timestamp DESC LIMIT 100").all(); return new Response(JSON.stringify(r.results||[]),{headers:cors});}
  const b=await request.json().catch(()=>({})); const {id,authorPhone,author,emoji,text,phase,isSehhar,action,postId,type,reactorPhone}=b;
  if(action==='create'){await DB.prepare("INSERT INTO posts (id,authorPhone,author,emoji,text,phase,timestamp,isSehhar,likedBy,heartedBy,coffeedBy,likes,hearts,coffees) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,'[]','[]','[]',0,0,0)").bind(id,authorPhone,author,emoji,text.slice(0,180),phase,Date.now(),isSehhar?1:0).run(); return new Response(JSON.stringify({ok:true}),{headers:cors});}
  if(action==='react'){const post=await DB.prepare("SELECT * FROM posts WHERE id=?1").bind(postId).first(); if(!post) return new Response(JSON.stringify({error:'not found'}),{status:404,headers:cors}); let liked=JSON.parse(post.likedBy||'[]'), hearted=JSON.parse(post.heartedBy||'[]'), coffeed=JSON.parse(post.coffeedBy||'[]'); let field,col,pts; if(type==='like'){field='likes';col='likedBy';pts=1} if(type==='heart'){field='hearts';col='heartedBy';pts=2} if(type==='coffee'){field='coffees';col='coffeedBy';pts=5} const arr=type==='like'?liked:type==='heart'?hearted:coffeed; const has=arr.includes(reactorPhone); if(has){const na=arr.filter(p=>p!==reactorPhone); await DB.prepare(`UPDATE posts SET ${field}=${field}-1, ${col}=?1 WHERE id=?2`).bind(JSON.stringify(na),postId).run(); await DB.prepare("UPDATE users SET points=MAX(0,points-?1) WHERE phone=?2").bind(pts,post.authorPhone).run();}else{arr.push(reactorPhone); await DB.prepare(`UPDATE posts SET ${field}=${field}+1, ${col}=?1 WHERE id=?2`).bind(JSON.stringify(arr),postId).run(); await DB.prepare("UPDATE users SET points=points+?1 WHERE phone=?2").bind(pts,post.authorPhone).run();} return new Response(JSON.stringify({ok:true}),{headers:cors});}
  return new Response(JSON.stringify({error:'action'}),{status:400,headers:cors});
}
